name: Dev Branch Migration Check

on:
  push:
    branches:
      - dev

jobs:
  migration-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          cd django
          poetry install

      - name: Remove existing migrations
        run: |
          cd django
          rm -f */migrations/0*.py

      - name: Make migrations
        run: |
          cd django
          poetry run python manage.py makemigrations --settings=a_core.settings.development

      - name: Run migrations
        run: |
          cd django
          poetry run python manage.py migrate --settings=a_core.settings.development
